package old.mdp2dtmc;

import java.util.ArrayList;
import java.util.List;

public class RewardItem {

	private String guard;
	private String reward;
	private String label;
	private String container;
	private List<Integer> states;
	private boolean isNeeded = false;
	private boolean autoGen = false;

	public RewardItem(String _label, String _guard, String _reward, String _container) {
		this.label = _label;
		this.guard = _guard;
		this.reward = _reward;
		this.container = _container;
	}

	public String getContainer() {
		return container;
	}

	public String getLabel() {
		return label;
	}

	public String getGuard() {
		return guard;
	}

	public String getReward() {
		return reward;
	}

	public void setGuard(String guard) {
		this.guard = guard;
	}

	public void setReward(String reward) {
		this.reward = reward;
	}

	public boolean isGuardAlwaysTrue() {
		if (guard.equals("true"))
			return true;
		return false;
	}

	public void setPartOfTransformationModel(boolean status) {
		isNeeded = true;
	}

	public boolean isPartOfTransformationModel() {
		return isNeeded;
	}

	public void setAutoGenerated(boolean autoGen) {
		this.autoGen = autoGen;
	}

	public boolean isAutoGenerated() {
		return autoGen;
	}

	public List<Integer> getStates() {
		if (states == null)
			states = new ArrayList<Integer>();
		return states;
	}
}
